# Generated by Django 4.0.10 on 2023-08-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('lic_expir_dd', models.DateField()),
                ('license_creation_date', models.DateField()),
                ('license_status', models.CharField(max_length=255, null=True)),
                ('license_type', models.CharField(max_length=255, null=True)),
                ('address_city', models.CharField(max_length=255, null=True)),
                ('address_state', models.CharField(max_length=255, null=True)),
                ('address_borough', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
